sudo: required
dist: trusty

language: haxe

haxe:
  # - "3.4.7"
  - "4.0.0-rc.3"
  - "development"

git:
  submodules: false

before_install:
  - git submodule update --init --remote --recursive
  - haxelib git rxhaxe https://github.com/darmie/RxHaxe
  - haxelib git Binary128 https://github.com/darmie/Binary128
  - haxelib git Numerix https://github.com/darmie/Numerix
  - haxelib install hexlog
  - haxelib install hxjava
  # - haxelib install hxcs

matrix:
  allow_failures:
    - haxe: development

# install:
#   - yes | haxelib install all

script:
  - haxe build.hxml


deploy:
  - provider: script
    haxe: 3.4.7
    script: bash ./release_haxelib.sh $HAXELIB_PWD
    on:
      tags: true