sudo: required
dist: trusty

language: haxe

haxe:
  - "3.4.7"
  - "development"

git:
  submodules: false

before_install:
  - git submodule update --init --remote --recursive
  - haxelib git rxhaxe https://github.com/longde123/RxHaxe
  - haxelib install hexlog

matrix:
  allow_failures:
    - haxe: development

# install:
#   - yes | haxelib install all

script:
  - haxe build.hxml


deploy:
  - provider: script
    haxe: 3.4.7
    script: bash ./release_haxelib.sh $HAXELIB_PWD
    on:
      tags: true